"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""

sumEvens = 0
a, b = 0, 1
my_sum = a + b
# What's the convention around these? Individual line? Multi-line?

for i in range (100):
    a = b
    b = my_sum
    my_sum = a + b
    if my_sum <= 4000000:
        # In Fibonacci series, every third value (from 2) is even, based on rules of adding evens and odds
        # Question: Would it be more efficient to run a loop incrementing by 3 instead of dividing each i?
        if i % 3 == 0:
            sumEvens += my_sum
            
print(sumEvens)
